# Generated by Django 3.0.11 on 2020-11-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
